PRODUCT_ENTRY = "product"
PRODUCT_VALUE = "EcoDevices_RT"

RESPONSE_ENTRY = "status"
RESPONSE_SUCCESS_VALUE = "Success"

ENOCEAN_GET_LINK = "Get=XENO"
ENOCEAN_SWITCH_GET_ENTRY = "ENO ACTIONNEUR%d"
ENOCEAN_SENSOR_GET_ENTRY = "ENO ANALOG%d"
ENOCEAN_SWITCH_ON_LINK = "SetEnoPC=%d"
ENOCEAN_SWITCH_OFF_LINK = "ClearEnoPC=%d"
ENOCEAN_SWITCH_TOGGLE_LINK = "ToggleEnoPC=%d"

INDEX_GET_LINK = "Index=All"

TOROID_GET_CONSUMPTION_ENTRY = "Index_TORE_Cons%d"
TOROID_GET_PRODUCTION_ENTRY = "Index_TORE_Dist%d"
TOROID_GET_ENTRY = "Index_TORE%d"

RELAY_GET_LINK = "Get=R"
RELAY_GET_ENTRY = "R%d"
RELAY_ON_LINK = "SetR=%02d"
RELAY_OFF_LINK = "ClearR=%02d"
RELAY_TOGGLE_LINK = "ToggleR=%02d"

VIRTUAL_OUTPUT_GET_LINK = "Get=VO"
VIRTUAL_OUTPUT_GET_ENTRY = "VO%d"
VIRTUAL_OUTPUT_ON_LINK = "SetVO=%03d"
VIRTUAL_OUTPUT_OFF_LINK = "ClearVO=%03d"
VIRTUAL_OUTPUT_TOGGLE_LINK = "ToggleVO=%03d"

DIGITAL_INPUT_GET_LINK = "Get=D"
DIGITAL_INPUT_GET_ENTRY = "D%d"

XTHL_GET_LINK = "Get=XTHL"
XTHL_GET_TMP_ENTRY = "THL%d-TEMP"
XTHL_GET_HUM_ENTRY = "THL%d-HUM"
XTHL_GET_LUM_ENTRY = "THL%d-LUM"

X4FP_GET_LINK = "Get=FP"
X4FP_GET_ENTRY = "FP%d Zone %d"
X4FP_SET_MODE_LINK = "SetFP%02d=%d"

X4FP_TO_VALUE = {
    "Confort": 0,
    "Eco": 1,
    "Hors Gel": 2,
    "Arret": 3,
    "Confort -1": 4,
    "Confort -2": 5
}

COUNTER_GET_LINK = "Get=C"
COUNTER_GET_ENTRY = "C%d"
COUNTER_SET_LINK = "SetC%02d=%s"
