name: Publish 📦 to PyPI and TestPyPI

on:
    release:
        types: [created]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    upload:
        name: Build and publish 📦 to PyPI and TestPyPI
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  # Upgrade pip
                  python -m pip install --upgrade pip
                  # Install build deps
                  pip install tox-gh-actions
                  # If requirements.txt exists, install from it
                  if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
            - name: Build and Install package
              run: |
                  # Build the packages
                  python setup.py sdist bdist_wheel

            - name: Publish distribution 📦 to Test PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                  password: ${{ secrets.TEST_PYPI_API_TOKEN }}
                  repository_url: https://test.pypi.org/legacy/
            - name: Publish distribution 📦 to PyPI
              if: startsWith(github.ref, 'refs/tags')
              uses: pypa/gh-action-pypi-publish@master
              with:
                  password: ${{ secrets.PYPI_API_TOKEN }}
